#!/bin/bash
# - MISC - 
VERSION="0.11"
USAGE="Usage: changext FROM TO"


# - CODE -
if [ $# == 0 ] ; then
    echo $VERSION
    echo $USAGE
    exit 1;

else
	 for file in *.$1
	   do
	     mv "$file" "${file%.$1}.$2"
	   done

fi
